note-store:
    max-note-length: 10000
    open-api-url: http://api:8080/notes
server:
  port: 8080
spring:
  datasource:
    password: mySecret
    url: jdbc:postgresql://postgres:5432/note
    username: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cloud:
   openfeign:
     client:
       config:
         FilesApiClient:
           url: http://file:8080